# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
---
version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    labels:
      - 'deps/github-actions'
    groups:
      all:
        patterns: ['*']
