# yaml-language-server: $schema=https://json.schemastore.org/prettierrc.json
---
printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: none
bracketSpacing: true
bracketSameLine: false
arrowParens: always
endOfLine: lf
embeddedLanguageFormatting: auto
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: true
