# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
---
name: Bot Details
description: 🤖 Get bot details (name, email, author/committer) in a proper format for the subsequence steps like git, PR, and more.
author: Dariusz Porowski
branding:
  icon: user # https://feathericons.com/
  color: gray-dark

inputs:
  bot-slug-name:
    description: Bot slug name (GitHub App name)
    required: false
    default: github-actions
  set-env:
    description: "Save action's output also as environment variables"
    default: "true"
  env-prefix:
    description: Prefix for environment variables
    required: false
  github-token:
    description: GitHub token to use for API authentication
    required: false
    default: ${{ github.token }}

outputs:
  id:
    description: Bot id
    value: ${{ steps.bot-details.outputs.id }}
  slug:
    description: Bot slug name
    value: ${{ steps.bot-details.outputs.slug }}
  name:
    description: Bot name
    value: ${{ steps.bot-details.outputs.name }}
  email:
    description: Bot email
    value: ${{ steps.bot-details.outputs.email }}
  name-email:
    description: Bot name and email
    value: ${{ steps.bot-details.outputs.name_email }}
  html-url:
    description: Bot html url
    value: ${{ steps.bot-details.outputs.html_url }}
  api-url:
    description: Bot api url
    value: ${{ steps.bot-details.outputs.api_url }}

runs:
  using: composite
  steps:
    - name: Get bot details
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: bot-details
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const path = require('path')
          const actionPath = path.join(process.env.GITHUB_ACTION_PATH, 'index.cjs')
          const script = require(actionPath)
          await script({ github, core })
      env:
        INPUT_BOT_SLUG_NAME: ${{ inputs.bot-slug-name }}
        INPUT_SET_ENV: ${{ inputs.set-env }}
        INPUT_ENV_PREFIX: ${{ inputs.env-prefix }}
